### ISSUE TITLE
Add cake-contrib user on Nuget.org

### ISSUE THREAD

**Issue by gep13** [AgileArchitect/Cake.Sonar#1]
Great work on getting this Addin created!

Just thought I would add this issue as a reminder that, if possible, it would be great to get the cake-contrib user added as a co-maintainer of the nuget package.  More information about this is detailed here:

http://cakebuild.net/blog/2016/08/cake-contribution-organization

If you have any questions, then please feel free to reach out and we can discuss.

Thanks again!

**Comment by gep13** [comment]
@tomstaijen thank you for adding the cake-contrib user to your NuGet package! :+1:

I will go ahead and close this issue, but just so I know, are you planning on wanting to move this addin into the cake-contrib organisation, and maintain it there, or would you like to keep it here?

Thanks again!

**Comment by tomstaijen** [comment]
@gep13 i don't mind moving it to cake-contrib.

**Comment by gep13** [comment]
@tomstaijen sweet! It isn't a requirement, so only if you want to. But it will give your repo a bit more visibility as well. If you want to go ahead, then if you transfer the repo to my GitHub account, gep13, I can transfer it to the organisation.

**Comment by gep13** [comment]
@tomstaijen just wanted to follow up to see if this is something that you are interested in doing. Thanks!
