### ISSUE TITLE
Custom SonarQube.Analysis.xml location

### ISSUE THREAD

**Issue by pmilbank** [AgileArchitect/Cake.Sonar#13]
Hi

Could it be possible to make a setting that allows a custom SonarQube.Analysis.xml location. Currently it defaults to a downloaded xml in MSBuild.SonarQube.Runner.Tool\tools. 

Thanks
Paul

**Comment by tomstaijen** [comment]
Example usage: 

`new SonarBeginSettings() { SettingsFile = "./analysis.xml" }`

Relative paths will be made absolute before passing it to the scanner.
