### ISSUE TITLE
Integration with TeamCity

### ISSUE THREAD

**Issue by miketonguk** [AgileArchitect/Cake.Sonar#14]
Not sure whether this is a problem with the addin or with my TC configuration. I have the integration working fine when running the cake script from the command line. However when run as a build step, the integration with MSBuild Breaks and I get this error.

<pre>The SonarQube MSBuild integration failed: SonarQube was unable to collect the required information about your projects.
Possible causes:
  1. The project has not been built - the project must be built in between the begin and end steps
  2. An unsupported version of MSBuild has been used to build the project. Currently MSBuild 12.0 upwards are supported
  3. The begin, build or end steps have not all been launched from the same folder
Generation of the sonar-properties file failed. Unable to complete SonarQube analysis.
</pre>

When I run from the command line, I'm running it from the TC Build Agent's working directory, so all files/paths/MSBuild versions etc are identical.

**Comment by miketonguk** [comment]
After a couple of days of detective work, I've tracked down the problem. The route cause was the sonar targets which are required to interate with MSBuild were not being picked up when MSbuild ran.

The reason for this was the the TeamCity build agent was running as Local System Account, this means the MSBuild directory it's using to store target files is:

<pre>C:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\MSBuild</pre>
However, the SonarQube.Scanner.MSBuild.exe is compiled for 32bit, so this path gets change during the emulation on 64bit OSs to:
<pre>C:\Windows\sysWOW4\config\systemprofile\AppData\Local\Microsoft\MSBuild</pre>
However, when the MSBuild step runs, that is 64bit, so it looks in the system32 folder!

You can try to change the user that the buildagent runs under, but that doesn't work. This is a quirk of how TeamCity Build agents work I believe. Basically, the appData folders in the environment settings don't get adjusted correctly.

The way I got it to work was to download the source for the sonarqube scanner and compile a 64bit version. 

Is there a way to have the plugin contain both the 32bit & 64bit versions of the sonarqube scanner and run the appropriate one based on the machines os?

**Comment by tomstaijen** [comment]
the scanner is a direct copy from the scanner project releases. maybe it's a good idea to ask there.
