### ISSUE TITLE
GitHub plugin arguments

### ISSUE THREAD

**Issue by erik-am** [AgileArchitect/Cake.Sonar#21]
Could the arguments required for the [GitHub plugin](https://docs.sonarqube.org/display/PLUG/GitHub+Plugin) be added?

* `sonar.analysis.mode`
* `sonar.github.oauth`
* `sonar.github.repository`
* `sonar.github.pullRequest`
* `sonar.github.endpoint`
* `sonar.github.disableInlineComments`

**Comment by tomstaijen** [comment]
Does the scanner's _end_ stage also need any of these settings?

**Comment by tomstaijen** [comment]
Otherwise you can use ArgumentCustomization for this on the beginsettings. 
See http://cakebuild.net/api/Cake.Core.Tooling/ToolSettings/50AAB3A8
