### ISSUE TITLE
ArgumentCustomization seems to be ignored

### ISSUE THREAD

**Issue by Roemer** [AgileArchitect/Cake.Sonar#23]
As the title says, additional arguments from the ```ArgumentCustomization``` seems to be ignored.

Examlple:
```csharp
SonarBegin(new SonarBeginSettings {
    Url = "...
    ArgumentCustomization = args => args
        .Append("/d:sonar.log.level=DEBUG")        
});
```

**Comment by Ky7m** [comment]
It seems to me that custom argument was overridden by addin's settings. 
I tried with argument that is not supported by addin and it works for me. https://github.com/AgileArchitect/Cake.Sonar/issues/26#issuecomment-320634458

**Comment by Roemer** [comment]
It actually is added just the log does not print it.

**Comment by Roemer** [comment]
PR #32 fixes that.

**Comment by tomstaijen** [comment]
merged now, thanks. closing this.
