### ISSUE TITLE
SonarEndSettings needed?

### ISSUE THREAD

**Issue by Roemer** [AgileArchitect/Cake.Sonar#25]
Why does SonarEnd need any settings? I haven't found any information from SonarQube that you can pass anything there which is used.

**Comment by tomstaijen** [comment]
Msbuild scanner docs say:

Sensitive properties such as "sonar.login" and "sonar.password" are not persisted on disk for security reasons. If you wish to pass them as command line arguments, you will have to so for both the "begin" and "end" steps.
