### ISSUE TITLE
Generic paramater method

### ISSUE THREAD

**Issue by WebDucer** [AgileArchitect/Cake.Sonar#28]
Sonaruqube can be extended with a lot of plugins. Some of them use specific sonar keys to configure the analysis run (e.g. GitLab). Instead of trying to match them all, it would be nice to have a generic way, like and extension methods in MSBuild implementation.

```csharp
var settings = new SonarBeginSettings {
            Key = projectId,
            Url = sonarUrl
    }
    .AddParameter("sonar.some.key", "some value");
```

**Comment by Roemer** [comment]
Just use ArgumentCustomization from the SonarBeginSettings.

**Comment by tomstaijen** [comment]
closing this as @Roemer's suggestion should suffice
