### ISSUE TITLE
Various paths are just strings and not "made absolut"

### ISSUE THREAD

**Issue by Roemer** [AgileArchitect/Cake.Sonar#31]
Many settings (e.g. NUnitReportsPath, DotCoverReportsPath, VsCoverageReportsPath) are just strings and therefore are not made absolute (and quoted after PR #30). I think they all should be of type FilePath so that they behave correctly.

**Comment by tomstaijen** [comment]
making paths absolute should not be required. the scanner supports relative paths just fine. going to  reverse this change in favor of #35
