### ISSUE TITLE
ReportPaths are only a single FilePath but sonar supports multiple

### ISSUE THREAD

**Issue by Roemer** [AgileArchitect/Cake.Sonar#35]
As the title says, all reportpaths are just a single FilePath but Sonar supports multiple (comma separated) as far as I know.

**Comment by javicrespo** [comment]
Same problem here. Sonar reports path supports wildcards (*) too, which FilePath doesn't

https://docs.sonarqube.org/pages/viewpage.action?pageId=6389770 (Importing Multiple Reports section)

In fact, it'd be enough to change the FilePath type to string, wouldn't it?

https://github.com/AgileArchitect/Cake.Sonar/blob/master/src/Cake.Sonar/SonarBeginSettings.cs#L89

**Comment by Roemer** [comment]
I'd prefer having a list of strings then. Then a user does not need to care about how the items in there needs to be concatinated or quoted.

**Comment by tomstaijen** [comment]
I agree. they were strings before but were changes to filepath to auto convert to absolute paths. However, 1) it's more important to support multiple files, 2) sonar can handle relative paths so why bother making them absolute, and 3) if you want to convert a path to absolute, you can do it in your cake script and then pass it as a string.

**Comment by tomstaijen** [comment]
solved in 1.0.2
