### ISSUE TITLE
Cake.Core reference issue

### ISSUE THREAD

**Issue by IulianGhinia** [AgileArchitect/Cake.Sonar#37]
Error: The assembly 'Cake.Sonar, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' is referencing an older version of Cake.Core (0.16.2). 
This assembly need to reference at least Cake.Core version 0.22.0.

**Comment by MarkWillems** [comment]
Same here

**Comment by rikribbers** [comment]
Same here, would provide a pull-request if I'm more skilled C# coder...

**Comment by tomstaijen** [comment]
Thanks!
