### ISSUE TITLE
sonar.branch has been deprecated

### ISSUE THREAD

**Issue by wwwlicious** [AgileArchitect/Cake.Sonar#40]
the following warning is produced in the logs:

`The use of "sonar.branch" is deprecated and replaced by "sonar.branch.name". See https://redirect.sonarsource.com/doc/branches.html`

Using sonarQube 6.7 LTS version, MSBuild.SonarQube.Runner.Tool v3.0.0 and Cake.Sonar v1.0.0.

**Comment by Roemer** [comment]
Same here. Not sure how to handle that correctly. Best would be if it would be possible to get the sonar version and do that automatically. Other possibilities would be a SonarVersion property where one could pass the version in use.

**Comment by philipooo** [comment]
Since `sonar.branch.name` seems to be a feature for payed versions of SonarQube/Branch Plugin only, I would like to see a way to configure `Cake.Sonar` which parameter should be used.

**Comment by s-pw** [comment]
There is free alternative now. See Branch Plugin for SonarQube Community Edition https://github.com/s-pw/sonar-branch-community

**Comment by thepieterdc** [comment]
The repository mentioned by @s-pw has been moved to https://github.com/msanez/sonar-branch-community
