### ISSUE TITLE
SonarEnd fails on build server but not on a local build.

### ISSUE THREAD

**Issue by B3nCr** [AgileArchitect/Cake.Sonar#48]
Hi

Sonar is failing to analyse my project when I run my cake script from the build agent.

It's pretty weird because I'm sure it was working but then stopped, seemingly randomly (although I probably just don't remember what I changed). I can run the cake build from the build agent folder and the the sonar steps execute fine which makes me think this might be a permissions issue?

I think the error message below must be some sort of red herring, we're not trying to generate code coverage. I did add a dotCover cake task but removed it again due to this error, I can't find any trace of dotcover in the folder any more, although the executable will still be in the path.

The project is being built with MSBuild 15. It's using version 25 of Cake and the latest release of Cake.Sonar.

I thought I'd seen somewhere that this issue might be caused by missing or incomplete windows updates or permissions issues but that might be a dotcover issue.

Cake.Sonar references a nuget package to get the sonar scanner command line and that nuget package is not using the latest version of the command line tool. It's got sonar-scanner-3.0.3.778 and there is a sonar-scanner-3.1.0.1141 version available but I'm not sure how to upgrade that to see if it fixes the issue.

Any help would be gratefully received. When I've got the build server back up and running again I'd also like to try and get dotCover running with Cake.Sonar but I was running into the same error (I thought that was a dotCover issue but maybe something else caused this issue and dotCover is a redherring).

Thanks
Ben

> 2018-03-15T23:01:06.8978276Z 23:01:06.897  23:01:06.893  WARNING: Failed to find the code coverage command line tool. Possible cause: Visual Studio is not installed, or the installed version does not support code coverage.
> 2018-03-15T23:01:06.9125207Z ##[error]The SonarQube MSBuild integration failed: SonarQube was unable to collect the required information about your projects.
> Possible causes:
>   1. The project has not been built - the project must be built in between the begin and end steps
>   2. An unsupported version of MSBuild has been used to build the project. Currently MSBuild 14.0 upwards are supported
>   3. The begin, build or end steps have not all been launched from the same folder
> 
> 2018-03-15T23:01:06.9135410Z Generation of the sonar-properties file failed. Unable to complete SonarQube analysis.
> 2018-03-15T23:01:06.9137037Z 23:01:06.913  Creating a summary markdown file...
> 2018-03-15T23:01:06.9895726Z ##[error]23:01:06.914  Post-processing failed. Exit code: 1
> An error occurred when executing task 'SonarEnd'.
> Error: One or more errors occurred.
> 	SonarQube: Process returned an error (exit code 1).

**Comment by B3nCr** [comment]
Forgot to mention, build agent is VSTS.

**Comment by tomstaijen** [comment]
Sorry for the late reply. Seems your SonarBegin isn't writing the required files or you're cleaning them before SonarEnd. A good start is to check your .sonarqube subfolder after SonarBegin.

**Comment by tomstaijen** [comment]
It's more of a sonarqube scanner problem though (the tool we call). You wight want to try calling that one without the plugin to see what's going on.
