### ISSUE TITLE
Files inclusion into SonarQube analysis  

### ISSUE THREAD

**Issue by citrucc** [AgileArchitect/Cake.Sonar#50]
Hi,

Is there any possibility to include files? I know that there is possibility to exclude file, but I didn't find the way how to include.

**Comment by tomstaijen** [comment]
There is [ArgumentCustomization in ToolSettings](https://cakebuild.net/api/Cake.Core.Tooling/ToolSettings/50AAB3A8) (which is a base class of . [SonarBeginSettings](https://cakebuild.net/api/Cake.Sonar/SonarBeginSettings/)) which you can use to configure the [Inclusions parameter](https://docs.sonarqube.org/display/SONAR/Analysis+Parameters#AnalysisParameters-Exclusions/Inclusions) of the tool.

**Comment by citrucc** [comment]
Hi Tomstaijen,

I tried to use ArgumentCustomization   as you suggested to me, but I got errors that Cake it seems doesn't know SonarQube commands, or I do something wrong. Could you please tell me what I do wrong. 

Task("Sonar-Init")
	.Does(() => {
		SonarBegin(new SonarBeginSettings{
		ArgumentCustomization = args => args.Append("-Dsonar.login=" + sonarLogin, "-Dsonar.password=" + sonarPassword, "sonar.projectKey=" + sonarKey, "-Dsonar.inclusions=SampleProject/**", "-Dsonar.host.url=" + sonarUrl, "-Dsonar.sources=SampleProject", "-Dsonar.projectVersion=1.0.1", "-Dsonar.projectName=TestPrpject")
		});
  }); 

Error output:

14:30:22.593  14:30:22.593  Unrecognized command line argument: -sonar.login=admin
14:30:22.608  14:30:22.593  A required argument is missing: /key:[SonarQube project key]

**Comment by citrucc** [comment]
I think I do something wrong or Cake doesn't understand Sonarqube commands.

**Comment by citrucc** [comment]
👎
