### ISSUE TITLE
Question: How to add "start" parameters?

### ISSUE THREAD

**Issue by o7g8** [AgileArchitect/Cake.Sonar#59]
Hello,

For integration with GitEnterprise and TeamCity I need to specify following SonarQube parameters:
```
/d:sonar.analysis.mode=
/d:sonar.useWsCache=
/d:sonar.issuesReport.html.enable=
/d:sonar.issuesReport.console.enable=
/d:sonar.language=
/d:sonar.github.pullRequest=
/d:sonar.github.repository=
/d:sonar.github.login=
/d:sonar.github.oauth=
/d:sonar.github.endpoint=
/d:sonar.github.deleteOldComments=
```

See also https://docs.sonarqube.org/display/PLUG/GitHub+Plugin

Is it correct that currently one need to add new properties into `SonarBeginSettings.cs`, which will reflect the additional Sonar parameters?

I wonder if it would make sense to allow Cake users to specify arbitrary Sonar parameters using a weakly typed interface (e.g. via a `Dictionary<string, string>` on `SonarBeginSettings `)? Would you accept such change?

Oleg

**Comment by tomstaijen** [comment]
You can specify custom attributes. SonarBeginSettings inherits from
ToolSettings which has a property ArgumentCustomization for that purpose.

**Comment by Tanzy** [comment]
Adding a `Dictionary<string, string>` makes sense to me, makes it easier when making running the task from CakeBuild

**Comment by o7g8** [comment]
I have posted a PR with "explicit" implementation of the parameters. 
I also think the `Dictionary<string,string>` would simplify life for many people, who use "less popular" SonarQube parameters and plugins. It can be implemented in the next PR.

**Comment by tomstaijen** [comment]
ArgumentCustomization in ToolSettings does the same thing. Why duplicate that.

https://cakebuild.net/api/Cake.Core.Tooling/ToolSettings/50AAB3A8
