### ISSUE TITLE
Setting Version causes Cake.Sonar to not setting VersionResult

### ISSUE THREAD

**Issue by philipooo** [AgileArchitect/Cake.Sonar#60]
Hi

First, thank you for this AddIn!

After the last update our build stopped working because the `sonar.branch.name` was set. As we have no license to use `sonar.branch.name` we are forced to use `sonar.branch`. We are using SonarQube 6.7.1, so this should be no problem because there is [code ](https://github.com/AgileArchitect/Cake.Sonar/blob/master/src/Cake.Sonar/SonarBeginSettings.cs#L63) to switch between these to parameters depending on the Version.
But this seemed not to work because `sonar.branch.name` still was set. As I inspected the plugin code I stumbled over this line of [code](https://github.com/AgileArchitect/Cake.Sonar/commit/f61eac36a38edf06d4052860d4db04af723e2b60#diff-9d21f98ac02a2ef02c84ee9606993d3aR43). I think checking `beginSettings.Version` is not correnct because it defines the project-version of the analysed project and not the version of SonarQube itself. So this check should be removed to still execute line 44 and set `VersionResult`.

Cheers Philip

**Comment by tomstaijen** [comment]
The Version you can set is the version of the project. That might actually map to sonar.projectVersion but i'm not sure. The sonar msbuild scanner has a /v option for it.

The VersionResult is about the version of your sonarqube server, which is decided by calling an API on your server.  When retrieving that version does not succeed, you will have a VersionResult.Exception, and it will fall back to the default Argument, which for branch is sonar.branch.name.

**Comment by tomstaijen** [comment]
It should be using sonar.branch whenever it detects a sonarqube instance with a version below 7.

**Comment by tomstaijen** [comment]
Sorry for the delay. Thanks for pointing that out!
