### ISSUE TITLE
Support for dotnetcore without installing msbuild

### ISSUE THREAD

**Issue by farodin91** [AgileArchitect/Cake.Sonar#63]
It would be cool to use sonarqube without msbuild
for example the code:

```
dotnet <path to SonarScanner.MSBuild.dll> begin /k:"project-key"
dotnet build
dotnet <path to SonarScanner.MSBuild.dll> end
```

**Comment by farodin91** [comment]
dublicated #46

**Comment by tomstaijen** [comment]
yes that would be cool, however, this is merely a cake plugin for specifically the msbuild sonar scanner.
