### ISSUE TITLE
RedirectStandardOutput should be false in silent mode?

### ISSUE THREAD

**Issue by GeertvanHorrik** [AgileArchitect/Cake.Sonar#66]
https://github.com/AgileArchitect/Cake.Sonar/blob/6de26247b3e067d8f2cd34e4cdc3329dd78a57e8/src/Cake.Sonar/SonarRunner.cs#L38

Shouldn't this be !SilentMode to suppress this info?

**Comment by tomstaijen** [comment]
Nope. It's a tricky one though. Had to read it a couple of times to figure it out. And of course it works the way it is used now.

https://msdn.microsoft.com/en-us/library/system.diagnostics.processstartinfo.redirectstandardoutput(v=vs.110).aspx

_When a Process writes text to its standard stream, that text is typically displayed on the console. By setting RedirectStandardOutput to true to redirect the StandardOutput stream, you can manipulate or suppress the output of a process._
