### ISSUE TITLE
How to fail the build when SQ fails?

### ISSUE THREAD

**Issue by GeertvanHorrik** [AgileArchitect/Cake.Sonar#70]
We are very happy with the integration with SQ. We have been spending 2 weeks on cleaning up our code base and think we are ready for our builds to fail whenever SQ fails.

Is there a way to fail a build? Note we want the results from the server (it has some "resolve as won't fix" configured stuff), not only local results.

I hope it's possible to get the results back while pushing to the server, and of course I am happy to PR something if it's not possible yet.

**Comment by tomstaijen** [comment]
This plugin cannot do that. 

There's probably some sonar api you can use to request the number of issues of the build and some baseline you can compare it with. 

I know that its possible using a sonar plugin for bitbucket. It's a long shot but that might work for you. You can configure it as a merge blocker on a pull request.

**Comment by GeertvanHorrik** [comment]
I am already building it, wanted to show it to you but it's not done yet ;-)

**Comment by GeertvanHorrik** [comment]
I think I got it working, here is the output:

```
The SonarQube Scanner has finished
19:48:27.044  Creating a summary markdown file...
19:48:27.053  Analysis results: https://[redacted]/dashboard/index/[redacted]
19:48:27.055  Post-processing succeeded.
Checking whether the project passed the SonarQube gateway...
SonarQube gateway status returned from request: 'OK'
The SonarQube gateway for '[redacted]' returned OK, well done! If you want to show off the results, check out https://[redacted]/dashboard?id=[redacted]
```

Here is the full script:

https://github.com/GeertvanHorrik/RepositoryTemplate/blob/master/replace/deployment/cake/tasks.cake#L108

Of course you are allowed to use any of it if you want to incorporate it into his extension.

**Comment by umairjadoon** [comment]
> I think I got it working, here is the output:
> 
> ```
> The SonarQube Scanner has finished
> 19:48:27.044  Creating a summary markdown file...
> 19:48:27.053  Analysis results: https://[redacted]/dashboard/index/[redacted]
> 19:48:27.055  Post-processing succeeded.
> Checking whether the project passed the SonarQube gateway...
> SonarQube gateway status returned from request: 'OK'
> The SonarQube gateway for '[redacted]' returned OK, well done! If you want to show off the results, check out https://[redacted]/dashboard?id=[redacted]
> ```
> 
> Here is the full script:
> 
> https://github.com/GeertvanHorrik/RepositoryTemplate/blob/master/replace/deployment/cake/tasks.cake#L108
> 
> Of course you are allowed to use any of it if you want to incorporate it into his extension.

The link you have provided is not working. I end up at https://github.com/GeertvanHorrik/RepositoryTemplate/blob/master/deployment/cake/tasks.cake but could not find anything related to gateway failure. Could you point me to the right source please?

**Comment by GeertvanHorrik** [comment]
It's in this finally block where we fail the build (including a link to the sonarqube gateway that failed):

https://github.com/GeertvanHorrik/RepositoryTemplate/blob/master/deployment/cake/tasks.cake#L345
