### ISSUE TITLE
Sonar End Permission denied in Docker Container.

### ISSUE THREAD

**Issue by HotdogWang** [AgileArchitect/Cake.Sonar#83]
Hi ,
I've using cake.sonar to scan my project in docker container.
But I get permission denied issue when cake build try to do Sonar end.

Below picture is for reference.
<img width="1409" alt="screen shot 2018-12-05 at 2 35 47 pm" src="https://user-images.githubusercontent.com/12172172/49494901-34d8a500-f89c-11e8-8198-b5d4d351ab88.png">

**Comment by tomstaijen** [comment]
Does your container have java installed?

**Comment by HotdogWang** [comment]
Hi @tomstaijen 
Thanks for your reply.
I finally to find solution is install **openjdk8-jre** in my container.

Link is my reference.
https://community.sonarsource.com/t/sonarscanner-fails-with-error-permission-denied/1897/6

:)
